name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml pull
          docker-compose -f docker-compose.yml build

      - name: Start services
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for webapp to be ready
        run: |
          timeout 60 sh -c 'until curl -s http://webapp:3100 > /dev/null; do sleep 2; done' || false

      - name: Run Playwright tests
        run: docker-compose -f docker-compose.yml run playwright

      - name: Clean up Docker Compose
        if: always()
        run: docker-compose -f docker-compose.yml down
